---
- hosts: all
  tasks:
    - name: Print something
      debug: msg="Hello!"
  tasks:
    - name: Install https transport package
      sudo: yes
      apt: name=apt-transport-https update_cache=yes state=present
  tasks:
    - name: Add Docker registry key
      sudo: yes
      apt_key: id=A88D21E9  url=http://get.docker.io/gpg state=present
  tasks:
    - name: Add Docker repository sources
      sudo: yes
      apt_repository: repo='deb http://get.docker.io/ubuntu docker main' update_cache=yes state=present 
  tasks:
    - name: Install Docker
      sudo: yes
      apt: name=lxc-docker update_cache=yes cache_valid_time=600 state=latest
